### PR TITLE
updated axios dependency to 0.21.1 to fix vulnerability

### PR DESCRIPTION
**Pull request by Dusch4593**
Hi Nishan! 

I wasn't sure how you felt about contributions to this repo. But I recently discovered this Gatsby plugin and was _excited_ because I'm currently building a portfolio site and I wanted to be able to add a feed of my recent blog posts on Hashnode. 

- Brandon (Massachusetts, US)

### CODE REVIEW

**Review by nishantwrp — APPROVED** [review]
Thanks for the contribution @Dusch4593. Contributions are very welcome to all my projects. :smile:

**Comment by Dusch4593** [comment]
No problem! Happy to help! I still can't seem to find the `allDevblogPost` section on GraphiQL though. I wonder if it's something else that's the problem? Should I open a separate issue on the "Issues" tab?

**Comment by nishantwrp** [comment]
Can you share your hashnode username so I can check if there's some fault in the code?

**Comment by Dusch4593** [comment]
@Dusch4593

**Comment by nishantwrp** [comment]
I discovered that there were problems due to the changed hashnode API. I've updated the code and documentation according to that. Please update to the latest version (0.2.0) of this plugin and try again.

**Comment by Dusch4593** [comment]
I found some success after updating the plugin and restarting the server. I am now able to query under `allDevBlogPost`. However, I wasn't able to `tags` in the tree on the left in GraphiQL: 

```
query MyQuery {
  allDevblogPost {
    edges {
      node {
        brief
        coverImage
        cuid
        dateAdded
        slug
        title
        type
        tags {
          name
        }
        id
      }
    }
  }
}
```

I went to read some of the documentation on [Hashnode's GraphQL API](https://engineering.hashnode.com/introducing-hashnode-graphql-api-public-beta-cjydzvp59001q2gs1b5zxaeaf) and saw in `tags` property in the code snippets. I wonder it's not showing up here?

**Comment by Dusch4593** [comment]
Screen Shot 2021-01-24 at 3 41 05 PM

**Comment by nishantwrp** [comment]
Hi @Dusch4593, here the error seems to be on Hashnode's side. Try to run the following query on [api.hashnode.com](https://api.hashnode.com).

```graphql
query{ user(username: "Dusch4593") { publication { posts { cuid slug title type dateUpdated dateAdded contentMarkdown brief coverImage tags { name }}}}}
```

You'll observe the following output for the `tags` field.

```json
{
  "tags": [
    {
      "name": null
    },
    {
      "name": null
     }
   ]
}
```

**Comment by Dusch4593** [comment]
You are right. It seems like it's pulling the amount of tag objects for each post, but their value is bad data. Hopefully, Hashnode will fix soon. Do you know if their API is maintained in a repo accepting issues?

**Comment by nishantwrp** [comment]
I don't know of any repo that tracks bugs in hashnode api, maybe just email them.

**Pull request merged**
